name: jogja_karir
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^9.0.0
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.1.0
  form_field_validator: ^1.1.0
  get: ^4.3.8
  google_sign_in: ^5.0.7
  image_picker: ^0.8.3+2
  provider: ^5.0.0

dev_dependencies:
  # flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

# flutter_icons:
#   ios: true
#   android: true
#   image_path_ios: "images/icon.jpg"
#   image_path_android: "images/icon.jpg"
#   adaptive_icon_background: "images/icon.jpg"
#   adaptive_icon_foreground: "images/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - images/
